'use strict';
// Zachowany adres i schemat danych z dostarczonego panelu.
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFC').trim().replace(/\s+/g,' ');
const fold=v=>norm(v).toLocaleLowerCase('pl');
const number=v=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:10}).format(v);
const gameByKey=k=>GAMES.find(g=>g.key===k);
const byScore=(a,b)=>b.score-a.score || ((a.ts||0)-(b.ts||0)) || a.id.localeCompare(b.id);
const trash='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v5M14 11v5"/></svg>';
let current='ninja',busy=false,readSequence=0,noticeTimeout=null,deleteTarget=null;
const cache=new Map(),drafts=new Map(),attempts=new Map();
function logo(g){return g.logo?`<img src="https://triki.zabka.pl/images/game-image-${g.logo}.png" alt="" loading="lazy">`:esc(g.short);}
function fallbackImages(){document.querySelectorAll('img').forEach(img=>{img.onerror=()=>{const host=img.parentElement;host.textContent=host.dataset.short||gameByKey(current).short;};});}
function notify(message,type='ok'){clearTimeout(noticeTimeout);$('notice').textContent=message;$('notice').className=type;$('notice').hidden=false;noticeTimeout=setTimeout(()=>{$('notice').hidden=true;},type==='error'?15000:6500);}
function state(title,detail,type){$('status-title').textContent=title;$('status-detail').textContent=detail;$('status-icon').className='status-icon '+type;}
function setBusy(value){busy=value;document.querySelectorAll('.game-tab').forEach(b=>b.disabled=value);$('submit-btn').disabled=value;$('refresh-btn').disabled=value;$('clear-btn').disabled=value||!cache.get(current)?.length;$('confirm-delete').disabled=value;$('cancel-delete').disabled=value;}
function renderNavigation(){ $('games').innerHTML=GAMES.map(g=>`<button class="game-tab ${g.key===current?'active':''}" data-game="${g.key}" aria-pressed="${g.key===current}" ${busy?'disabled':''}><span class="game-icon" data-short="${g.short}">${logo(g)}</span>${g.label}</button>`).join('');$('games').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>switchGame(btn.dataset.game)));fallbackImages();}
function saveDraft(){const form=$('entry-form');const draft={};for(const el of form.elements)if(el.name)draft[el.name]=el.value;drafts.set(current,draft);}
function switchGame(key){if(busy||key===current)return;saveDraft();current=key;readSequence++;renderNavigation();renderGame();loadList();}
function renderGame(){document.querySelector('.tv-link').href='tv.html?game='+current;const g=gameByKey(current),duel=current==='snake1v1';document.documentElement.style.setProperty('--accent',g.color);$('game-art').dataset.short=g.short;$('game-art').innerHTML=logo(g);$('game-title').textContent=g.label;$('game-kind').textContent=duel?'POJEDYNEK 1 NA 1':'GRA PUNKTOWA';$('game-rule').textContent=duel?'Zapisuj zwycięzcę i przegranego':'Wyższy wynik wygrywa';$('game-number').innerHTML=`${String(GAMES.indexOf(g)+1).padStart(2,'0')} <i>/ ${String(GAMES.length).padStart(2,'0')}</i>`;$('footer-game').textContent=g.label;$('count-label').textContent=duel?'Zapisane mecze':'Zapisane wyniki';$('best-label').textContent=duel?'Najwięcej zwycięstw':'Najlepszy wynik';$('entry-title').textContent=duel?'Dodaj mecz':'Dodaj wynik';$('results-title').textContent=duel?'Ostatnie mecze':'Aktualne wyniki';$('clear-description').textContent=`Usuwanie obejmie wyłącznie grę ${g.label}.`;$('clear-btn').textContent=duel?'Wyczyść mecze tej gry':'Wyczyść wyniki tej gry';$('results-footer').textContent=duel?'Najnowsze mecze na górze. Lider według liczby zwycięstw.':'Każdy wpis to osobna próba. Równe wyniki mają wspólne miejsce.';renderForm();renderResults(cache.get(current));fallbackImages();}
function field(id,label,type,placeholder,extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" ${extra} aria-describedby="${id}-error"><p class="field-error" id="${id}-error"></p></div>`;}
function renderForm(){const duel=current==='snake1v1';$('entry-form').innerHTML=duel?`${field('winner','Zwycięzca','text','Nick zwycięzcy','maxlength="48" autocomplete="off" required')}${field('loser','Przegrany','text','Nick przegranego','maxlength="48" autocomplete="off" required')}<button class="button save-button" id="submit-btn" type="submit">Zapisz mecz <span>+</span></button><p class="form-message" id="form-message" role="status" aria-live="polite"></p>`:`${field('name','Nick gracza','text','np. ShadowFox','maxlength="48" autocomplete="off" required')}<div class="form-row">${field('score','Wynik','number','np. 1250','min="0" step="any" inputmode="decimal" required')}${field('jury','Nr jury <span class="optional">(opcjonalnie)</span>','number','np. 2','min="1" step="1" inputmode="numeric"')}</div><button class="button save-button" id="submit-btn" type="submit">Zapisz wynik <span>+</span></button><p class="form-message" id="form-message" role="status" aria-live="polite"></p>`;const draft=drafts.get(current)||{};for(const [key,value]of Object.entries(draft))if($(key))$(key).value=value;$('entry-form').onsubmit=submitEntry;}
function validate(data,key){const errors={};if(key==='snake1v1'){for(const name of ['winner','loser'])if(!norm(data[name])||norm(data[name]).length>48)errors[name]='Podaj nick (maks. 48 znaków).';if(norm(data.winner)&&norm(data.loser)&&fold(data.winner)===fold(data.loser))errors.loser='Zwycięzca i przegrany muszą być różnymi graczami.';return{errors,payload:{winner:norm(data.winner),loser:norm(data.loser)}};}
 if(!norm(data.name)||norm(data.name).length>48)errors.name='Podaj nick (maks. 48 znaków).';const score=Number(data.score);if(String(data.score??'').trim()===''||!Number.isFinite(score)||score<0||score>Number.MAX_SAFE_INTEGER)errors.score='Podaj poprawny wynik: zero lub liczbę dodatnią.';const payload={name:norm(data.name),score};if(String(data.jury??'').trim()!==''){const jury=Number(data.jury);if(!Number.isSafeInteger(jury)||jury<1)errors.jury='Podaj dodatni, całkowity numer jury.';else payload.jury=jury;}return{errors,payload};}
function showErrors(errors){let first=null;for(const el of $('entry-form').elements){if(!el.name)continue;const error=errors[el.name];el.setAttribute('aria-invalid',String(!!error));const target=$(el.name+'-error');if(target)target.textContent=error||'';if(error&&!first)first=el;}first?.focus();}
function formMessage(message,type){$('form-message').textContent=message;$('form-message').className='form-message '+type;}
async function request(path,options={}){const aborter=new AbortController(),timeout=setTimeout(()=>aborter.abort(),15000);try{const response=await fetch(`${DB}/${path}.json`,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})},signal:aborter.signal});if(!response.ok){const e=new Error(`HTTP ${response.status}`);e.status=response.status;throw e;}return await response.json();}finally{clearTimeout(timeout);}}
function errorText(error){if(error.status===401||error.status===403)return'Brak uprawnień do bazy. Sprawdź reguły dostępu w Firebase.';if(error.name==='AbortError')return'Przekroczono czas oczekiwania. Sprawdź połączenie.';return'Nie udało się połączyć z bazą. Sprawdź internet i spróbuj ponownie.';}
function parseRecords(value,key){if(value===null)return{items:[],invalid:0};if(typeof value!=='object'||Array.isArray(value))throw new Error('Niepoprawny format danych');let invalid=0;const items=[];for(const [id,row]of Object.entries(value)){if(!row||typeof row!=='object'||Array.isArray(row)){invalid++;continue;}if(key==='snake1v1'){if(typeof row.winner!=='string'||typeof row.loser!=='string'||!norm(row.winner)||!norm(row.loser)){invalid++;continue;}items.push({...row,id});}else{if(typeof row.name!=='string'||!norm(row.name)||typeof row.score!=='number'||!Number.isFinite(row.score)){invalid++;continue;}items.push({...row,id});}}return{items,invalid};}
function rankPlayers(items){const wins=new Map();for(const row of items){const key=fold(row.winner);const old=wins.get(key)||{name:row.winner,wins:0};old.wins++;wins.set(key,old);}return [...wins.values()].sort((a,b)=>b.wins-a.wins||a.name.localeCompare(b.name,'pl'));}
function updateMetrics(items){const valid=Array.isArray(items);$('metric-count').textContent=valid?number(items.length):'—';$('list-count').textContent=valid?number(items.length):'—';$('clear-btn').disabled=busy||!valid||!items.length;if(!valid||!items.length){$('metric-best').textContent='—';$('metric-leader').textContent='—';return;}let leaders,score;if(current==='snake1v1'){const ranked=rankPlayers(items);score=ranked[0]?.wins||0;leaders=ranked.filter(x=>x.wins===score).map(x=>x.name);}else{score=Math.max(...items.map(x=>x.score));leaders=[...new Set(items.filter(x=>x.score===score).map(x=>x.name))];}$('metric-best').textContent=number(score);$('metric-leader').textContent=leaders.length>1?`${leaders.length} graczy ex aequo`:leaders[0];$('metric-leader').title=leaders.join(', ');}
function emptyState(title,detail,retry=false){return`<div class="empty-state"><span class="empty-mark" aria-hidden="true">${retry?'!':'—'}</span><h3>${esc(title)}</h3><p>${esc(detail)}</p>${retry?'<button class="button secondary" id="retry-load">Spróbuj ponownie</button>':''}</div>`;}
function renderResults(items){updateMetrics(items);const body=$('results-body');if(!items){body.innerHTML=emptyState('Pobieramy wyniki','Za chwilę pojawią się tutaj wpisy z bazy wydarzenia.');return;}if(!items.length){body.innerHTML=emptyState(current==='snake1v1'?'Pierwszy mecz przed nami':'Czekamy na pierwszy wynik',current==='snake1v1'?'Dodaj zakończony pojedynek, aby rozpocząć zestawienie.':'Dodaj wynik w formularzu. Tutaj pojawi się ranking gry.');return;}
 const duel=current==='snake1v1',rows=[...items].sort(duel?((a,b)=>(Number(b.ts)||0)-(Number(a.ts)||0)||b.id.localeCompare(a.id)):byScore);let rank=1;body.innerHTML=`<div class="table-scroll"><table><caption class="sr-only">${esc(gameByKey(current).label)} — ${duel?'zapisane mecze':'wszystkie zapisane wyniki'}</caption><thead><tr>${duel?'<th scope="col">Mecz</th><th scope="col">Zwycięzca / przegrany</th><th scope="col">Zapisano</th>':'<th scope="col">#</th><th scope="col">Gracz</th><th scope="col" style="text-align:center">Jury</th><th scope="col" style="text-align:right">Wynik</th>'}<th scope="col"><span class="sr-only">Usuń</span></th></tr></thead><tbody>${rows.map((row,i)=>{if(!duel&&(i===0||row.score!==rows[i-1].score))rank=i+1;return`<tr class="${!duel&&rank===1?'top-rank':''}"><td class="place">${duel?String(rows.length-i).padStart(2,'0'):String(rank).padStart(2,'0')}</td>${duel?`<td class="player"><span class="match-win">${esc(row.winner)}</span><span class="match-vs">vs ${esc(row.loser)}</span></td><td class="jury">${typeof row.ts==='number'&&Number.isFinite(row.ts)?esc(new Date(row.ts).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})):'—'}</td>`:`<td class="player">${esc(row.name)}${row.round?`<span class="subline">Runda ${esc(row.round)}</span>`:''}</td><td class="jury">${Number.isSafeInteger(row.jury)&&row.jury>0?`<span>${row.jury}</span>`:'—'}</td><td class="score">${number(row.score)}</td>`}<td><button class="delete-row" data-delete="${esc(row.id)}" aria-label="Usuń ${esc(duel?'mecz '+row.winner+' z '+row.loser:'wynik gracza '+row.name)}" ${busy?'disabled':''}>${trash}</button></td></tr>`;}).join('')}</tbody></table></div>`;body.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>openDelete(btn.dataset.delete)));}
async function loadList({quiet=false}={}){const key=current,seq=++readSequence;if(!quiet){$('results-body').setAttribute('aria-busy','true');$('refresh-btn').disabled=true;state('Odświeżanie wyników','Pobieramy dane z bazy','loading');}try{const value=await request(key);if(key!==current||seq!==readSequence)return;const {items,invalid}=parseRecords(value,key);cache.set(key,items);renderResults(items);state(invalid?'Część wpisów wymaga sprawdzenia':'Połączono z bazą',`Aktualizacja ${new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`,invalid?'error':'ok');if(invalid)notify(`Pominięto ${invalid} niepoprawnych wpisów w widoku. Dane w bazie nie zostały zmienione.`,'error');}catch(error){if(key!==current||seq!==readSequence)return;state('Brak aktualnych danych',cache.has(key)?'Pokazujemy ostatnio pobrane wyniki':'Sprawdź połączenie z bazą','error');if(!cache.has(key)){$('results-body').innerHTML=emptyState('Nie można pobrać wyników',errorText(error),true);$('retry-load').onclick=()=>loadList();}if(!quiet)notify(errorText(error),'error');}finally{if(key===current&&seq===readSequence){$('results-body').setAttribute('aria-busy','false');$('refresh-btn').disabled=busy;}}}
async function submitEntry(event){event.preventDefault();if(busy)return;const data={};for(const el of $('entry-form').elements)if(el.name)data[el.name]=el.value;const {payload,errors}=validate(data,current);showErrors(errors);if(Object.keys(errors).length)return;const key=current;const fingerprint=JSON.stringify(payload);let attempt=attempts.get(key);if(!attempt||attempt.fingerprint!==fingerprint){attempt={fingerprint,id:'entry_'+crypto.randomUUID(),payload:{...payload,ts:{'.sv':'timestamp'}}};attempts.set(key,attempt);}setBusy(true);formMessage('Zapisujemy…','');$('submit-btn').textContent='Zapisywanie…';try{await request(`${key}/${attempt.id}`,{method:'PUT',body:JSON.stringify(attempt.payload)});attempts.delete(key);for(const id of ['name','score','winner','loser'])if($(id))$(id).value='';saveDraft();formMessage(key==='snake1v1'?'Mecz został zapisany.':'Wynik został zapisany.','ok');notify(key==='snake1v1'?`Zapisano mecz: ${payload.winner} vs ${payload.loser}.`:`Zapisano: ${payload.name} — ${number(payload.score)} pkt.`);await loadList({quiet:true});$(key==='snake1v1'?'winner':'name').focus();}catch(error){formMessage(`${errorText(error)} Nie potwierdzono zapisu. Odśwież listę. Ponowny zapis tych samych danych użyje tego samego wpisu.`,'error');state('Nie potwierdzono zapisu','Odśwież listę przed następnym wpisem','error');}finally{setBusy(false);$('submit-btn').innerHTML=`${key==='snake1v1'?'Zapisz mecz':'Zapisz wynik'} <span>+</span>`;}}
function openDelete(id=null){if(busy)return;const g=gameByKey(current),item=id?cache.get(current)?.find(x=>x.id===id):null;if(id&&!item)return;if(!id&&!cache.get(current)?.length)return;deleteTarget={key:current,id,label:g.label};const name=item?(current==='snake1v1'?`${item.winner} vs ${item.loser}`:`${item.name} — ${number(item.score)} pkt`):null;$('dialog-title').textContent=id?'Usunąć ten wpis?':`Wyczyścić ${g.label}?`;$('dialog-description').textContent=id?`Usuniesz wpis „${name}” z bazy wydarzenia. Zniknie również z tablicy wyników. Tej operacji nie można cofnąć.`:`Usuniesz wszystkie aktualne wyniki gry ${g.label} z bazy wydarzenia i tablicy wyników. Tej operacji nie można cofnąć.`;$('confirm-input-wrap').hidden=!!id;$('confirm-input').value='';$('confirm-input').placeholder=g.label;$('confirm-error').textContent='';$('confirm-delete').textContent=id?'Usuń wpis':'Usuń wszystkie wyniki';$('confirm-dialog').showModal();$('cancel-delete').focus();}
async function confirmDelete(event){event.preventDefault();if(busy||!deleteTarget)return;const target={...deleteTarget};if(!target.id&&fold($('confirm-input').value)!==fold(target.label)){$('confirm-error').textContent=`Wpisz dokładnie nazwę gry: ${target.label}.`;$('confirm-input').focus();return;}setBusy(true);$('confirm-delete').textContent='Usuwanie…';try{await request(target.id?`${target.key}/${target.id}`:target.key,{method:'DELETE'});$('confirm-dialog').close();deleteTarget=null;notify(target.id?'Wpis został usunięty.':`Wyczyszczono wyniki: ${target.label}.`);await loadList({quiet:true});}catch(error){$('confirm-dialog').close();deleteTarget=null;notify(`${errorText(error)} Nie potwierdzono usunięcia — odśwież listę.`,'error');}finally{setBusy(false);}}
// Cytowanie pól + neutralizacja formuł chronią raport otwierany w Excelu.
function csvCell(value){let s=String(value??'');if(/^[\s\uFEFF]*[=+\-@]/u.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return'"'+s.replace(/"/g,'""')+'"';}
function buildReport(all){const rows=[['PODSUMOWANIE'],['Gra','Liczba wpisów','Liderzy ex aequo','Najlepszy wynik / zwycięstwa']];for(const {g,items}of all){if(!items.length){rows.push([g.label,0,'','']);continue;}if(g.key==='snake1v1'){const ranked=rankPlayers(items),max=ranked[0].wins;rows.push([g.label,items.length,ranked.filter(x=>x.wins===max).map(x=>x.name).join(' / '),`${max} zwycięstw`]);}else{const sorted=[...items].sort(byScore),max=sorted[0].score;rows.push([g.label,items.length,[...new Set(sorted.filter(x=>x.score===max).map(x=>x.name))].join(' / '),max]);}}rows.push([]);for(const {g,items}of all){rows.push([g.label]);if(g.key==='snake1v1'){rows.push(['Zwycięzca','Przegrany','Czas zapisu']);for(const x of [...items].sort((a,b)=>(Number(b.ts)||0)-(Number(a.ts)||0)))rows.push([x.winner,x.loser,validDate(x.ts)]);}else{rows.push(['Miejsce','Nick','Wynik','Jury','Runda','Czas zapisu']);const sorted=[...items].sort(byScore);let rank=1;sorted.forEach((x,i)=>{if(i===0||x.score!==sorted[i-1].score)rank=i+1;rows.push([rank,x.name,x.score,x.jury??'',x.round??'',validDate(x.ts)]);});}rows.push([]);}return'\uFEFF'+rows.map(row=>row.map(csvCell).join(';')).join('\r\n');}
function validDate(ts){if(typeof ts!=='number'||!Number.isFinite(ts))return'';const date=new Date(ts);return Number.isNaN(date.getTime())?'':date.toISOString();}
async function downloadReport(){const btn=$('report-btn');if(btn.disabled)return;btn.disabled=true;btn.textContent='Przygotowujemy raport…';try{const all=await Promise.all(GAMES.map(async g=>{const value=await request(g.key);const parsed=parseRecords(value,g.key);if(parsed.invalid)throw new Error('invalid_records');return{g,items:parsed.items};}));if(!all.some(x=>x.items.length)){notify('Brak zapisanych wyników do wyeksportowania.','error');return;}const blob=new Blob([buildReport(all)],{type:'text/csv;charset=utf-8;'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`raport-triki-${new Date().toISOString().slice(0,19).replace(/[T:]/g,'-')}.csv`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);notify(`Raport wszystkich ${GAMES.length} gier jest gotowy.`);}catch(error){notify(error.message==='invalid_records'?'Raport nie został pobrany: część wpisów w bazie ma niepoprawny format. Nie wygenerowano niepełnego raportu.':`Nie pobrano pełnego raportu. ${errorText(error)}`,'error');}finally{btn.disabled=false;btn.innerHTML='<span aria-hidden="true">↓</span> Pobierz raport CSV';}}
$('refresh-btn').onclick=()=>{if(!busy)loadList();};$('report-btn').onclick=downloadReport;$('clear-btn').onclick=()=>openDelete();$('confirm-form').onsubmit=confirmDelete;$('cancel-delete').onclick=()=>{if(!busy){$('confirm-dialog').close();deleteTarget=null;}};$('confirm-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();else deleteTarget=null;});
window.addEventListener('online',()=>{if(!busy)loadList();});
window.addEventListener('offline',()=>state('Brak internetu','Zapisywanie wymaga połączenia','error'));
renderNavigation();renderGame();loadList();
setInterval(()=>{if(document.visibilityState==='visible'&&!busy&&!$('confirm-dialog').open)loadList({quiet:true});},20000);
