'use strict';
// Zachowany adres i schemat danych z dostarczonego panelu.
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').normalize('NFC').trim().replace(/\s+/g,' ');
const fold=v=>norm(v).toLocaleLowerCase('pl');
const numberFormatter=new Intl.NumberFormat('pl-PL',{maximumFractionDigits:10});
const number=v=>numberFormatter.format(v);
const gameByKey=k=>GAMES.find(g=>g.key===k);
const byScore=(a,b)=>b.score-a.score || ((a.ts||0)-(b.ts||0)) || a.id.localeCompare(b.id);
const trash='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" aria-hidden="true"><path d="M4 7h16M9 7V4h6v3M6 7l1 13h10l1-13M10 11v5M14 11v5"/></svg>';
const requestedGame=typeof location==='undefined'?null:new URLSearchParams(location.search).get('game');
let current=GAMES.some(g=>g.key===requestedGame)?requestedGame:'ninja',busy=false,readSequence=0,noticeTimeout=null,deleteTarget=null;
const cache=new Map(),drafts=new Map(),attempts=new Map();
const PAGE_SIZE=50;let resultPage=0,liveFeed=null,listPending=null;let historyMode=false,editTarget=null;
function logo(g){if(g.asset)return `<img src="${g.asset}" alt="" loading="lazy">`;return g.logo?`<img src="https://triki.zabka.pl/images/game-image-${g.logo}.png" alt="" loading="lazy">`:esc(g.short);}
function fallbackImages(){document.querySelectorAll('img').forEach(img=>{img.onerror=()=>{const host=img.parentElement;host.textContent=host.dataset.short||gameByKey(current).short;};});}
function notify(message,type='ok'){clearTimeout(noticeTimeout);$('notice').textContent=message;$('notice').className=type;$('notice').hidden=false;noticeTimeout=setTimeout(()=>{$('notice').hidden=true;},type==='error'?15000:6500);}
function state(title,detail,type){$('status-title').textContent=title;$('status-detail').textContent=detail;$('status-icon').className='status-icon '+type;}
function setBusy(value){busy=value;document.querySelectorAll('.game-tab,.delete-row,.edit-row').forEach(b=>b.disabled=value);$('submit-btn').disabled=value;$('refresh-btn').disabled=value;$('clear-btn').disabled=value||!cache.get(current)?.length;$('confirm-delete').disabled=value;$('cancel-delete').disabled=value;}
function renderNavigation(){ $('games').innerHTML=GAMES.map(g=>`<button class="game-tab ${g.key===current?'active':''}" data-game="${g.key}" aria-pressed="${g.key===current}" ${busy?'disabled':''}><span class="game-icon" data-short="${g.short}">${logo(g)}</span>${g.label}</button>`).join('');$('games').querySelectorAll('button').forEach(btn=>btn.addEventListener('click',()=>switchGame(btn.dataset.game)));fallbackImages();}
function saveDraft(){const form=$('entry-form');const draft={};for(const el of form.elements)if(el.name)draft[el.name]=el.value;drafts.set(current,draft);}
function switchGame(key){if(busy||key===current)return;saveDraft();liveFeed?.stop();current=key;resultPage=0;historyMode=false;readSequence++;renderNavigation();renderGame();startLive();}
function renderGame(){document.querySelector('.tv-link').href=testLink('tv.html?game='+current);const g=gameByKey(current),duel=current==='snake1v1';document.documentElement.style.setProperty('--accent',g.color);$('game-art').dataset.short=g.short;$('game-art').innerHTML=logo(g);$('game-title').textContent=g.label;$('game-kind').textContent=duel?'POJEDYNEK 1 NA 1':'GRA PUNKTOWA';$('game-rule').textContent=duel?'Zapisuj zwycięzcę i przegranego':'Wyższy wynik wygrywa';$('game-number').innerHTML=`${String(GAMES.indexOf(g)+1).padStart(2,'0')} <i>/ ${String(GAMES.length).padStart(2,'0')}</i>`;$('footer-game').textContent=g.label;$('count-label').textContent=duel?'Zapisane mecze':'Gracze w rankingu';$('best-label').textContent=duel?'Najwięcej zwycięstw':'Najlepszy wynik';$('entry-title').textContent=duel?'Dodaj mecz':'Dodaj wynik';$('results-title').textContent=duel?'Ostatnie mecze':'Aktualne wyniki';$('clear-description').textContent=`Usuwanie obejmie wyłącznie grę ${g.label}.`;$('clear-btn').textContent=duel?'Wyczyść mecze tej gry':'Wyczyść wyniki tej gry';$('results-footer').textContent=duel?'Najnowsze mecze na górze. Lider według liczby zwycięstw.':'Jeden najlepszy wynik na gracza. Wszystkie próby pozostają w historii i raporcie.';$('history-toggle').hidden=duel;renderForm();renderResults(cache.get(current));fallbackImages();}
function field(id,label,type,placeholder,extra=''){return `<div class="field"><label for="${id}">${label}</label><input id="${id}" name="${id}" type="${type}" placeholder="${placeholder}" ${extra} aria-describedby="${id}-error"><p class="field-error" id="${id}-error"></p></div>`;}
function renderForm(){const duel=current==='snake1v1';$('entry-form').innerHTML=duel?`${field('winner','Zwycięzca','text','Nick zwycięzcy','maxlength="48" autocomplete="off" required')}${field('loser','Przegrany','text','Nick przegranego','maxlength="48" autocomplete="off" required')}<button class="button save-button" id="submit-btn" type="submit">Zapisz mecz <span>+</span></button><p class="form-message" id="form-message" role="status" aria-live="polite"></p>`:`${field('name','Nick gracza','text','np. ShadowFox','maxlength="48" autocomplete="off" required')}<div class="form-row">${field('score','Wynik','number','np. 1250','min="0" step="any" inputmode="decimal" required')}${field('jury','Nr jury <span class="optional">(opcjonalnie)</span>','number','np. 2','min="1" step="1" inputmode="numeric"')}</div><button class="button save-button" id="submit-btn" type="submit">Zapisz wynik <span>+</span></button><p class="form-message" id="form-message" role="status" aria-live="polite"></p>`;const draft=drafts.get(current)||{};for(const [key,value]of Object.entries(draft))if($(key))$(key).value=value;$('entry-form').onsubmit=submitEntry;}
function validate(data,key){const errors={};if(key==='snake1v1'){for(const name of ['winner','loser'])if(!norm(data[name])||norm(data[name]).length>48)errors[name]='Podaj nick (maks. 48 znaków).';if(norm(data.winner)&&norm(data.loser)&&fold(data.winner)===fold(data.loser))errors.loser='Zwycięzca i przegrany muszą być różnymi graczami.';return{errors,payload:{winner:norm(data.winner),loser:norm(data.loser)}};}
 if(!norm(data.name)||norm(data.name).length>48)errors.name='Podaj nick (maks. 48 znaków).';const score=Number(data.score);if(String(data.score??'').trim()===''||!Number.isFinite(score)||score<0||score>Number.MAX_SAFE_INTEGER)errors.score='Podaj poprawny wynik: zero lub liczbę dodatnią.';const payload={name:norm(data.name),score};if(String(data.jury??'').trim()!==''){const jury=Number(data.jury);if(!Number.isSafeInteger(jury)||jury<1)errors.jury='Podaj dodatni, całkowity numer jury.';else payload.jury=jury;}return{errors,payload};}
function showErrors(errors){let first=null;for(const el of $('entry-form').elements){if(!el.name)continue;const error=errors[el.name];el.setAttribute('aria-invalid',String(!!error));const target=$(el.name+'-error');if(target)target.textContent=error||'';if(error&&!first)first=el;}first?.focus();}
function formMessage(message,type){$('form-message').textContent=message;$('form-message').className='form-message '+type;}
async function request(path,options={}){const aborter=new AbortController(),timeout=setTimeout(()=>aborter.abort(),15000);try{const response=await fetch(`${DB}/${path}.json`,{cache:'no-store',...options,headers:{'Content-Type':'application/json',...(options.headers||{})},signal:aborter.signal});if(!response.ok){const e=new Error(`HTTP ${response.status}`);e.status=response.status;throw e;}return await response.json();}finally{clearTimeout(timeout);}}
function errorText(error){if(error.status===401||error.status===403)return'Brak uprawnień do bazy. Sprawdź reguły dostępu w Firebase.';if(error.name==='AbortError')return'Przekroczono czas oczekiwania. Sprawdź połączenie.';return'Nie udało się połączyć z bazą. Sprawdź internet i spróbuj ponownie.';}
function parseRecords(value,key){if(value===null)return{items:[],invalid:0};if(typeof value!=='object'||Array.isArray(value))throw new Error('Niepoprawny format danych');let invalid=0;const items=[];for(const [id,row]of Object.entries(value)){if(!row||typeof row!=='object'||Array.isArray(row)){invalid++;continue;}if(key==='snake1v1'){if(typeof row.winner!=='string'||typeof row.loser!=='string'||!norm(row.winner)||!norm(row.loser)){invalid++;continue;}items.push({...row,id});}else{if(typeof row.name!=='string'||!norm(row.name)||typeof row.score!=='number'||!Number.isFinite(row.score)){invalid++;continue;}items.push({...row,id});}}return{items,invalid};}
function rankPlayers(items){const wins=new Map();for(const row of items){const key=fold(row.winner);const old=wins.get(key)||{name:row.winner,wins:0};old.wins++;wins.set(key,old);}return [...wins.values()].sort((a,b)=>b.wins-a.wins||a.name.localeCompare(b.name,'pl'));}
function updateMetrics(items){if(Array.isArray(items)&&current!=='snake1v1')items=TrikiRanking.best(items);const valid=Array.isArray(items);$('metric-count').textContent=valid?number(items.length):'—';$('list-count').textContent=valid?number(items.length):'—';$('clear-btn').disabled=busy||!valid||!items.length;if(!valid||!items.length){$('metric-best').textContent='—';$('metric-leader').textContent='—';return;}let leaders,score;if(current==='snake1v1'){const ranked=rankPlayers(items);score=ranked[0]?.wins||0;leaders=ranked.filter(x=>x.wins===score).map(x=>x.name);}else{score=items.reduce((max,x)=>Math.max(max,x.score),-Infinity);leaders=[...new Set(items.filter(x=>x.score===score).map(x=>x.name))];}$('metric-best').textContent=number(score);$('metric-leader').textContent=leaders.length>1?`${leaders.length} graczy ex aequo`:leaders[0];$('metric-leader').title=leaders.join(', ');}
function emptyState(title,detail,retry=false){return`<div class="empty-state"><span class="empty-mark" aria-hidden="true">${retry?'!':'—'}</span><h3>${esc(title)}</h3><p>${esc(detail)}</p>${retry?'<button class="button secondary" id="retry-load">Spróbuj ponownie</button>':''}</div>`;}
function renderResults(items){updateMetrics(items);$('history-toggle').textContent=historyMode?'Pokaż ranking':'Historia prób';$('history-toggle').setAttribute('aria-pressed',String(historyMode));$('results-title').textContent=current==='snake1v1'?'Ostatnie mecze':historyMode?'Historia prób':'Najlepsze wyniki';if(items&&current!=='snake1v1'&&!historyMode)items=TrikiRanking.best(items);if(items)$('list-count').textContent=number(items.length);const body=$('results-body');if(!items){body.innerHTML=emptyState('Pobieramy wyniki','Za chwilę pojawią się tutaj wpisy z bazy wydarzenia.');return;}if(!items.length){body.innerHTML=emptyState(current==='snake1v1'?'Pierwszy mecz przed nami':'Czekamy na pierwszy wynik',current==='snake1v1'?'Dodaj zakończony pojedynek, aby rozpocząć zestawienie.':'Dodaj wynik w formularzu. Tutaj pojawi się ranking gry.');return;}
 const duel=current==='snake1v1',rows=[...items].sort(duel?((a,b)=>(Number(b.ts)||0)-(Number(a.ts)||0)||b.id.localeCompare(a.id)):byScore);const pageCount=Math.ceil(rows.length/PAGE_SIZE);resultPage=Math.min(resultPage,pageCount-1);const start=resultPage*PAGE_SIZE;let rank=start+1;if(!duel){while(rank>1&&rows[rank-2].score===rows[start].score)rank--;}body.innerHTML=`<div class="table-scroll"><table><caption class="sr-only">${esc(gameByKey(current).label)} — ${duel?'zapisane mecze':'wszystkie zapisane wyniki'}</caption><thead><tr>${duel?'<th scope="col">Mecz</th><th scope="col">Zwycięzca / przegrany</th><th scope="col">Zapisano</th>':'<th scope="col">#</th><th scope="col">Gracz</th><th scope="col" style="text-align:center">Jury</th><th scope="col" style="text-align:right">Wynik</th>'}<th scope="col"><span class="sr-only">Działania</span></th></tr></thead><tbody>${rows.slice(start,start+PAGE_SIZE).map((row,localIndex)=>{const i=start+localIndex;if(!duel&&(i===0||row.score!==rows[i-1].score))rank=i+1;return`<tr class="${!duel&&rank===1?'top-rank':''}"><td class="place">${duel?String(rows.length-i).padStart(2,'0'):String(rank).padStart(2,'0')}</td>${duel?`<td class="player"><span class="match-win">${esc(row.winner)}</span><span class="match-vs">vs ${esc(row.loser)}</span></td><td class="jury">${typeof row.ts==='number'&&Number.isFinite(row.ts)?esc(new Date(row.ts).toLocaleString('pl-PL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})):'—'}</td>`:`<td class="player">${esc(row.name)}${row.round?`<span class="subline">Runda ${esc(row.round)}</span>`:''}</td><td class="jury">${Number.isSafeInteger(row.jury)&&row.jury>0?`<span>${row.jury}</span>`:'—'}</td><td class="score">${number(row.score)}</td>`}<td><div class="row-actions"><button type="button" class="edit-row" data-edit="${esc(row.id)}" ${busy?'disabled':''} aria-label="Edytuj ${esc(duel?'mecz '+row.winner+' z '+row.loser:'wynik gracza '+row.name)}">Edytuj</button><button class="delete-row" data-delete="${esc(row.id)}" aria-label="Usuń ${esc(duel?'mecz '+row.winner+' z '+row.loser:'wynik gracza '+row.name)}" ${busy?'disabled':''}>${trash}</button></div></td></tr>`;}).join('')}</tbody></table></div><div class="pagination"><button class="button secondary" id="page-prev" ${resultPage===0?'disabled':''}>← Poprzednia</button><span role="status">${start+1}–${Math.min(start+PAGE_SIZE,rows.length)} z ${number(rows.length)} · strona ${resultPage+1}/${pageCount}</span><button class="button secondary" id="page-next" ${resultPage+1>=pageCount?'disabled':''}>Następna →</button></div>`;$('page-prev').onclick=()=>{resultPage--;renderResults(cache.get(current));};$('page-next').onclick=()=>{resultPage++;renderResults(cache.get(current));};body.querySelectorAll('[data-edit]').forEach(btn=>btn.addEventListener('click',()=>openEdit(btn.dataset.edit)));body.querySelectorAll('[data-delete]').forEach(btn=>btn.addEventListener('click',()=>openDelete(btn.dataset.delete)));}
async function loadList({quiet=false}={}){if(quiet&&(liveFeed?.isLive||listPending===current))return;const key=current,seq=++readSequence;listPending=key;if(!quiet){$('results-body').setAttribute('aria-busy','true');$('refresh-btn').disabled=true;state('Odświeżanie wyników','Pobieramy dane z bazy','loading');}try{const value=await request(key);if(key!==current||seq!==readSequence)return;const {items,invalid}=parseRecords(value,key);cache.set(key,items);renderResults(items);state(invalid?'Część wpisów wymaga sprawdzenia':'Połączono z bazą',`Aktualizacja ${new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}`,invalid?'error':'ok');if(invalid)notify(`Pominięto ${invalid} niepoprawnych wpisów w widoku. Dane w bazie nie zostały zmienione.`,'error');}catch(error){if(key!==current||seq!==readSequence)return;state('Brak aktualnych danych',cache.has(key)?'Pokazujemy ostatnio pobrane wyniki':'Sprawdź połączenie z bazą','error');if(!cache.has(key)){$('results-body').innerHTML=emptyState('Nie można pobrać wyników',errorText(error),true);$('retry-load').onclick=()=>loadList();}if(!quiet)notify(errorText(error),'error');}finally{if(listPending===key)listPending=null;if(key===current&&seq===readSequence){$('results-body').setAttribute('aria-busy','false');$('refresh-btn').disabled=busy;}}}
async function submitEntry(event){event.preventDefault();if(busy)return;const data={};for(const el of $('entry-form').elements)if(el.name)data[el.name]=el.value;const {payload,errors}=validate(data,current);showErrors(errors);if(Object.keys(errors).length)return;const key=current;const fingerprint=JSON.stringify(payload);let attempt=attempts.get(key);if(!attempt||attempt.fingerprint!==fingerprint){attempt={fingerprint,id:'entry_'+crypto.randomUUID(),payload:{...payload,ts:{'.sv':'timestamp'}}};attempts.set(key,attempt);}setBusy(true);formMessage('Zapisujemy…','');$('submit-btn').textContent='Zapisywanie…';try{await request(`${key}/${attempt.id}`,{method:'PUT',body:JSON.stringify(attempt.payload)});attempts.delete(key);for(const id of ['name','score','winner','loser'])if($(id))$(id).value='';saveDraft();formMessage(key==='snake1v1'?'Mecz został zapisany.':'Próba zapisana. Ranking pokazuje najlepszy wynik gracza.','ok');notify(key==='snake1v1'?`Zapisano mecz: ${payload.winner} vs ${payload.loser}.`:`Zapisano: ${payload.name} — ${number(payload.score)} pkt.`);resultPage=0;await loadList({quiet:true});$(key==='snake1v1'?'winner':'name').focus();}catch(error){formMessage(`${errorText(error)} Nie potwierdzono zapisu. Odśwież listę. Ponowny zapis tych samych danych użyje tego samego wpisu.`,'error');state('Nie potwierdzono zapisu','Odśwież listę przed następnym wpisem','error');}finally{setBusy(false);$('submit-btn').innerHTML=`${key==='snake1v1'?'Zapisz mecz':'Zapisz wynik'} <span>+</span>`;}}
function openDelete(id=null){if(busy)return;const g=gameByKey(current),item=id?cache.get(current)?.find(x=>x.id===id):null;if(id&&!item)return;if(!id&&!cache.get(current)?.length)return;deleteTarget={key:current,id,label:g.label};const name=item?(current==='snake1v1'?`${item.winner} vs ${item.loser}`:`${item.name} — ${number(item.score)} pkt`):null;$('dialog-title').textContent=id?'Usunąć ten wpis?':`Wyczyścić ${g.label}?`;$('dialog-description').textContent=id?`Usuniesz wpis „${name}” z bazy wydarzenia. Zniknie również z raportu. Jeśli gracz ma inne próby, ranking pokaże najlepszą z pozostałych. Tej operacji nie można cofnąć.`:`Usuniesz wszystkie aktualne wyniki gry ${g.label} z bazy wydarzenia i tablicy wyników. Tej operacji nie można cofnąć.`;$('confirm-input-wrap').hidden=!!id;$('confirm-input').value='';$('confirm-input').placeholder=g.label;$('confirm-error').textContent='';$('confirm-delete').textContent=id?'Usuń wpis':'Usuń wszystkie wyniki';$('confirm-dialog').showModal();$('cancel-delete').focus();}
async function confirmDelete(event){event.preventDefault();if(busy||!deleteTarget)return;const target={...deleteTarget};if(!target.id&&fold($('confirm-input').value)!==fold(target.label)){$('confirm-error').textContent=`Wpisz dokładnie nazwę gry: ${target.label}.`;$('confirm-input').focus();return;}setBusy(true);$('confirm-delete').textContent='Usuwanie…';try{await request(target.id?`${target.key}/${target.id}`:target.key,{method:'DELETE'});$('confirm-dialog').close();deleteTarget=null;notify(target.id?'Wpis został usunięty.':`Wyczyszczono wyniki: ${target.label}.`);await loadList({quiet:true});}catch(error){$('confirm-dialog').close();deleteTarget=null;notify(`${errorText(error)} Nie potwierdzono usunięcia — odśwież listę.`,'error');}finally{setBusy(false);}}
function buildReport(all){
 const summary=[['Gra','Liczba wpisów','Liderzy ex aequo','Najlepszy wynik / zwycięstwa']],sheets=[];
 for(const {g,items}of all){
  const duel=g.key==='snake1v1';
  if(!items.length)summary.push([g.label,0,'','']);
  else if(duel){const ranked=rankPlayers(items),max=ranked[0].wins;summary.push([g.label,items.length,ranked.filter(x=>x.wins===max).map(x=>x.name).join(' / '),max]);}
  else{const records=TrikiRanking.best(items),max=records.reduce((v,x)=>Math.max(v,x.score),-Infinity);summary.push([g.label,items.length,records.filter(x=>x.score===max).map(x=>x.name).join(' / '),max]);}
  let rows;
  if(duel){rows=[['Zwycięzca','Przegrany','Czas zapisu (Europe/Warsaw)']];for(const x of [...items].sort((a,b)=>(Number(b.ts)||0)-(Number(a.ts)||0)))rows.push([x.winner,x.loser,validDate(x.ts)]);}
  else{rows=[['Miejsce w rankingu','Nick','Wynik','Jury','Runda','Czas zapisu (Europe/Warsaw)','Status próby']];const best=TrikiRanking.best(items).sort(byScore),ranks=new Map();let rank=1;best.forEach((x,i)=>{if(i===0||x.score!==best[i-1].score)rank=i+1;ranks.set(x.id,rank);});for(const x of [...items].sort(byScore))rows.push([ranks.get(x.id)??'',x.name,x.score,x.jury??'',x.round??'',validDate(x.ts),ranks.has(x.id)?'Najlepszy wynik':'Historia']);}
  sheets.push({name:g.label,rows,widths:duel?[30,30,32]:[22,30,18,12,15,32,22]});
 }
 const corrections=[['Gra','ID próby','Czas korekty (Europe/Warsaw)','Przed korektą','Po korekcie']];for(const {g,items} of all)for(const row of items)for(const edit of Object.values(row._edits||{})){if(edit&&typeof edit==='object')corrections.push([g.label,row.id,validDate(edit.ts),JSON.stringify(edit.before??{}),JSON.stringify(edit.after??{})]);}if(corrections.length>1)sheets.push({name:'Historia korekt',rows:corrections,widths:[24,44,32,60,60]});
 return TrikiExcel.workbook([{name:'Podsumowanie',rows:summary,widths:[24,18,55,32]},...sheets]);
}
const reportDateFormatter=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Warsaw',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'});
function validDate(ts){if(typeof ts!=='number'||!Number.isFinite(ts))return'';const date=new Date(ts);return Number.isNaN(date.getTime())?'':reportDateFormatter.format(date);}
async function downloadReport(){const btn=$('report-btn');if(btn.disabled)return;btn.disabled=true;btn.textContent='Przygotowujemy raport…';try{const all=await Promise.all(GAMES.map(async g=>{const value=await request(g.key);const parsed=parseRecords(value,g.key);if(parsed.invalid)throw new Error('invalid_records');return{g,items:parsed.items};}));if(!all.some(x=>x.items.length)){notify('Brak zapisanych wyników do wyeksportowania.','error');return;}const blob=buildReport(all),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`raport-triki-${validDate(Date.now()).replace(/[ :]/g,'-')}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);notify(`Raport wszystkich ${GAMES.length} gier jest gotowy.`);}catch(error){notify(error.message==='invalid_records'?'Raport nie został pobrany: część wpisów w bazie ma niepoprawny format. Nie wygenerowano niepełnego raportu.':`Nie pobrano pełnego raportu. ${errorText(error)}`,'error');}finally{btn.disabled=false;btn.innerHTML='<span aria-hidden="true">↓</span> Pobierz raport Excel';}}
function startLive(){
 liveFeed?.stop();const key=current;
 liveFeed=FirebaseFeed.watch(key,value=>{
  if(key!==current)return;
  try{const {items,invalid}=parseRecords(value,key);readSequence++;cache.set(key,items);renderResults(items);$('results-body').setAttribute('aria-busy','false');$('refresh-btn').disabled=busy;state(invalid?'Pominięto błędne wpisy':'Połączono na żywo',`Aktualizacja ${new Date().toLocaleTimeString('pl-PL')}`,invalid?'error':'ok');}
  catch{state('Błędne dane','Nie można odczytać rankingu','error');}
 },status=>{if(key!==current)return;if(status==='connected')return;state(status==='denied'?'Brak dostępu do bazy':'Łączenie z bazą…','Ponawianie połączenia','error');});
 if(typeof EventSource==='undefined')loadList();
}
function editSnapshot(row){const out={...row};delete out.id;return out;}
function stable(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return '['+value.map(stable).join(',')+']';return '{'+Object.keys(value).sort().map(k=>JSON.stringify(k)+':'+stable(value[k])).join(',')+'}';}
function editValues(row,key){const names=key==='snake1v1'?['winner','loser']:['name','score','jury'];return Object.fromEntries(names.filter(k=>row[k]!==undefined).map(k=>[k,row[k]]));}
function openEdit(id){
 if(busy)return;const row=cache.get(current)?.find(x=>x.id===id);if(!row)return;
 editTarget={key:current,id,original:JSON.parse(JSON.stringify(editSnapshot(row))),pending:null};
 const names=current==='snake1v1'?[['winner','Zwycięzca','text'],['loser','Przegrany','text']]:[['name','Nick gracza','text'],['score','Wynik','number'],['jury','Nr jury (opcjonalnie)','number']];
 $('edit-fields').innerHTML=names.map(([key,label,type])=>`<div class="field"><label for="edit-${key}">${label}</label><input id="edit-${key}" name="${key}" type="${type}" value="${esc(row[key]??'')}" ${type==='text'?'maxlength="48"':key==='jury'?'min="1" step="1"':'min="0" step="any"'}></div>`).join('');
 $('edit-error').textContent='';$('edit-dialog').showModal();$('edit-fields').querySelector('input')?.focus();
}
async function readForEdit(path){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),15000);try{const r=await fetch(`${DB}/${path}.json`,{headers:{'X-Firebase-ETag':'true'},cache:'no-store',signal:ctrl.signal});if(!r.ok){const e=new Error('http');e.status=r.status;throw e;}const etag=r.headers.get('ETag');if(!etag)throw new Error('Nie można bezpiecznie odczytać wersji wpisu. Spróbuj ponownie.');return{value:await r.json(),etag};}finally{clearTimeout(timer);}}
async function saveEdit(event){
 event.preventDefault();if(busy||!editTarget)return;const target=editTarget,data={};for(const input of $('edit-form').elements)if(input.name)data[input.name]=input.value;
 const {payload,errors}=validate(data,target.key);if(Object.keys(errors).length){$('edit-error').textContent=Object.values(errors).join(' ');return;}
 const fingerprint=stable(payload);if(!target.pending||target.pending.fingerprint!==fingerprint)target.pending={id:'edit_'+crypto.randomUUID(),fingerprint};
 setBusy(true);$('save-edit').disabled=true;$('cancel-edit').disabled=true;$('edit-error').textContent='Zapisywanie korekty…';
 try{const path=target.key+'/'+encodeURIComponent(target.id),{value,etag}=await readForEdit(path);
  if(!value)throw Error('Ten wpis został usunięty. Zamknij okno i odśwież listę.');
  if(!value._edits?.[target.pending.id]){
   if(stable(value)!==stable(target.original))throw Error('Ten wpis został zmieniony na innym stanowisku. Zamknij okno i otwórz edycję ponownie.');
   const next={...value,...payload};if(target.key!=='snake1v1'&&!('jury' in payload))delete next.jury;
   next._edits={...(value._edits||{}),[target.pending.id]:{before:editValues(value,target.key),after:payload,ts:{'.sv':'timestamp'}}};
   await request(path,{method:'PUT',headers:{'if-match':etag},body:JSON.stringify(next)});
  }
  $('edit-dialog').close();editTarget=null;notify('Korekta zapisana. Ranking zostanie przeliczony; historia korekt jest w raporcie.');await loadList();
 }catch(e){$('edit-error').textContent=e.status===412?'Wpis zmienił się podczas zapisu. Zamknij okno i otwórz edycję ponownie.':e.status?errorText(e):e.name==='AbortError'?'Nie potwierdzono zapisu. Spróbuj ponownie — korekta nie zostanie zdublowana.':e.message;}
 finally{setBusy(false);$('save-edit').disabled=false;$('cancel-edit').disabled=false;}
}
$('history-toggle').onclick=()=>{if(busy)return;historyMode=!historyMode;resultPage=0;renderResults(cache.get(current));};
$('edit-form').onsubmit=saveEdit;$('cancel-edit').onclick=()=>{if(!busy){$('edit-dialog').close();editTarget=null;}};
$('edit-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();else editTarget=null;});
$('refresh-btn').onclick=()=>{if(!busy)loadList();};$('report-btn').onclick=downloadReport;$('clear-btn').onclick=()=>openDelete();$('confirm-form').onsubmit=confirmDelete;$('cancel-delete').onclick=()=>{if(!busy){$('confirm-dialog').close();deleteTarget=null;}};$('confirm-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();else deleteTarget=null;});
window.addEventListener('online',()=>{if(!busy)loadList();});
window.addEventListener('offline',()=>state('Brak internetu','Zapisywanie wymaga połączenia','error'));
renderNavigation();renderGame();startLive();
setInterval(()=>{if(document.visibilityState==='visible'&&!busy&&!$('confirm-dialog').open)loadList({quiet:true});},20000);
