'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=v=>new Intl.NumberFormat('pl-PL',{maximumFractionDigits:10}).format(v);
const normalized=v=>v.normalize('NFC').trim().replace(/\s+/g,' ').toLocaleLowerCase('pl');
const requested=new URLSearchParams(location.search).get('game');
let current=GAMES.some(g=>g.key===requested)?requested:GAMES[0].key;
let revision=0,pending=null,messageTimer=null;
const snapshots=new Map();
function buildRanking(value,key){if(value===null)return{rows:[],invalid:0};if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('format');let invalid=0;const rows=[];
 if(key==='snake1v1'){const players=new Map();for(const match of Object.values(value)){if(!match||typeof match.winner!=='string'||!match.winner.trim()||typeof match.loser!=='string'||!match.loser.trim()){invalid++;continue;}for(const name of [match.winner,match.loser]){const id=normalized(name);if(!players.has(id))players.set(id,{id,name:name.trim(),score:0});}players.get(normalized(match.winner)).score++;}rows.push(...players.values());}
 else{for(const [id,row]of Object.entries(value)){if(!row||typeof row.name!=='string'||!row.name.trim()||typeof row.score!=='number'||!Number.isFinite(row.score)){invalid++;continue;}rows.push({id,name:row.name,score:row.score,ts:typeof row.ts==='number'?row.ts:0});}}
 rows.sort((a,b)=>b.score-a.score||(a.ts||0)-(b.ts||0)||a.id.localeCompare(b.id));let rank=1;rows.forEach((row,i)=>{if(!i||row.score!==rows[i-1].score)rank=i+1;row.rank=rank;});return{rows,invalid};}
function setStatus(message,type){$('status-text').textContent=message;$('status-light').className=type;}
function showMessage(text){clearTimeout(messageTimer);$('screen-message').hidden=false;$('screen-message').textContent=text;messageTimer=setTimeout(()=>{$('screen-message').hidden=true;},6000);}
function renderGame(){const index=GAMES.findIndex(g=>g.key===current),g=GAMES[index],duel=current==='snake1v1';document.documentElement.style.setProperty('--accent',g.color);$('game-title').textContent=g.label;$('next-game').textContent='Następna: '+GAMES[(index+1)%GAMES.length].label;$('game-counter').innerHTML=`${String(index+1).padStart(2,'0')} <i>/ ${String(GAMES.length).padStart(2,'0')}</i>`;$('game-short').textContent=g.short;$('ranking-rule').textContent=duel?'Najwięcej zwycięstw wygrywa':'Wyższy wynik wygrywa';$('points-label').textContent=duel?'WYGRANE':'PUNKTY';$('leader-unit').textContent=duel?'ZWYCIĘSTW':'PUNKTÓW';document.querySelector('.leader>.eyebrow').textContent=duel?'NAJWIĘCEJ ZWYCIĘSTW':'NAJLEPSZY WYNIK';$('ranking-note').textContent=(duel?'Ranking zwycięstw':'Każdy wpis to osobna próba')+' · odświeżanie co 10 s';$('change-game').setAttribute('aria-label','Zmień grę na '+GAMES[(index+1)%GAMES.length].label);document.title=g.label+' — TRIKI TV';renderBoard(snapshots.get(current));}
function renderBoard(data){const rows=data?.rows;if(!rows?.length){$('ranking-list').hidden=true;$('ranking-list').innerHTML='';$('empty').hidden=false;$('empty').innerHTML=data?'<strong>Czekamy na pierwszy wynik</strong><span>Po zapisaniu w panelu obsługi wynik pojawi się tutaj automatycznie.</span>':'<strong>Pobieramy wyniki</strong><span>Łączymy się z bazą wydarzenia.</span>';$('leader-name').textContent=data?'Kto będzie pierwszy?':'Ładowanie…';$('leader-name').className='';$('leader-score').textContent='—';$('leader-note').textContent='';return;}
 $('empty').hidden=true;$('ranking-list').hidden=false;const leader=rows[0],ties=rows.filter(r=>r.score===leader.score);$('leader-name').textContent=leader.name;$('leader-name').classList.toggle('long',leader.name.length>22);$('leader-score').textContent=fmt(leader.score);$('leader-score').classList.toggle('long',fmt(leader.score).length>10);$('leader-note').textContent=ties.length>1?`Wspólne 1. miejsce · ${ties.length} ${current==='snake1v1'?'graczy':'wpisów'}`:'Pierwsze miejsce w rankingu';$('ranking-list').innerHTML=rows.slice(0,10).map(row=>{const score=fmt(row.score);return`<li class="rank-row ${row.rank===1?'first':''}"><span class="rank-number">${String(row.rank).padStart(2,'0')}</span><span class="rank-name ${row.name.length>22?'long':''}" title="${esc(row.name)}">${esc(row.name)}</span><span class="rank-score ${score.length>10?'long':''}" title="${esc(score)}">${score}</span></li>`;}).join('');}
async function refresh(){if(pending?.key===current)return;const key=current,version=++revision,controller=new AbortController();pending={key,controller};$('board').setAttribute('aria-busy','true');const timeout=setTimeout(()=>controller.abort(),12000);if(!snapshots.has(key))setStatus('Łączenie z bazą…','');try{const response=await fetch(`${DB}/${key}.json`,{cache:'no-store',signal:controller.signal});if(!response.ok){const error=new Error('http');error.status=response.status;throw error;}const data=buildRanking(await response.json(),key);if(version!==revision||key!==current)return;snapshots.set(key,data);renderBoard(data);const time=new Date().toLocaleTimeString('pl-PL',{hour:'2-digit',minute:'2-digit',second:'2-digit'});setStatus(data.invalid?`Aktualizacja ${time} · pominięto ${data.invalid} błędnych wpisów`:`Aktualizacja ${time}`,data.invalid?'error':'ok');}catch(error){if(version!==revision||key!==current)return;const denied=error.status===401||error.status===403;setStatus(snapshots.has(key)?'Brak aktualizacji · pokazujemy ostatnio pobrane wyniki':denied?'Brak dostępu do bazy':'Brak połączenia · ponawiamy co 10 s','error');if(!snapshots.has(key)){$('empty').innerHTML=`<strong>${denied?'Brak dostępu do wyników':'Nie udało się pobrać wyników'}</strong><span>${denied?'Sprawdź uprawnienia do bazy w panelu obsługi.':'Sprawdź internet. Tablica spróbuje ponownie automatycznie.'}</span>`;$('leader-name').textContent='Czekamy na wyniki';}}finally{clearTimeout(timeout);if(version===revision){pending=null;$('board').setAttribute('aria-busy','false');}}}
function changeGame(){pending?.controller.abort();pending=null;revision++;const index=GAMES.findIndex(g=>g.key===current);current=GAMES[(index+1)%GAMES.length].key;const url=new URL(location.href);url.searchParams.set('game',current);try{history.replaceState(null,'',url);}catch{}setStatus('Odświeżanie wyników…','');renderGame();refresh();}
async function fullscreen(){try{if(document.fullscreenElement){await document.exitFullscreen();}else if(document.documentElement.requestFullscreen){await document.documentElement.requestFullscreen();}else{showMessage('Użyj opcji pełnego ekranu w menu przeglądarki.');}}catch{showMessage('Nie można włączyć pełnego ekranu. Użyj opcji w menu przeglądarki.');}}
$('change-game').onclick=changeGame;$('fullscreen').onclick=fullscreen;document.addEventListener('fullscreenchange',()=>{$('fullscreen').textContent=document.fullscreenElement?'Zamknij pełny ekran ⛶':'Pełny ekran ⛶';});window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>setStatus('Brak internetu · wyniki mogą być nieaktualne','error'));document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')refresh();});renderGame();refresh();setInterval(()=>{if(document.visibilityState==='visible')refresh();},10000);
